name: CI

on: [push]

jobs:
  golang-job:
    runs-on: ubuntu-latest
    container:
      image: golang:1.13
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: ls -la
        run: ls -la
      - name: go version
        run: go version
